name: AutoVersion

on:
  schedule:
  - cron: '33 3 * * *'
  push:
    branches: [master]

env:
  AssemblyInfo: ./src/Properties/AssemblyInfo.cs

jobs:
  autoversion:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Change version
        run: >
          (Get-Content ${{env.AssemblyInfo}}) -replace
          '(?<start>(AssemblyInfo|AssemblyFileVersion)\(\"\d{4}\.)\d{2}(?<end>(\.\*|\.0\.0)"\))',
          "`${start}$(Get-Date -format 'MM')`${end}" 
          | Set-Content ${{ env.AssemblyInfo }}
      - name: Commit changes
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git fetch
          git add ${{ env.AssemblyInfo }}
          git commit -m "Auto update version to $((Get-Culture).DateTimeFormat.GetMonthName((Get-Date -format 'MM'))) $(Get-Date -format 'yyyy')" 
          git push -f origin master