name: AutoVersion

on:
  schedule:
  - cron: '*/2 * * * *'
  push:
    branches: [ master ]

jobs:
  autoversion:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get time
        run: $Time = Get-Date
      - name: Replace version
        run: |
          Set-Content 'version.cs' $Time
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git fetch
          git add *
          git commit -am "Auto version update" 
          git push -f origin master