name: AutoVersion

on:
  schedule:
  - cron: '33 3 * * *'
  push:
    branches: [master]

jobs:
  autoversion:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get Mounth
        run: $Month = Get-Date -format 'mm'
      - name: Get AssemblyInfo path
        run: $File = 'src/Properties/AssemblyInfo.cs'
      - name: Change version
        run: >
          (Get-Content $File) -replace
          '(?<start>(AssemblyVersion|AssemblyFileVersion)\(\"\d{4}\.)\d{2}(?<end>(\.\*|\.0\.0)"\))',
          "`${start}$Month`${end}" 
          | Set-Content $File
      - name: Commit changes
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git fetch
          git add $File
          git commit -m "Auto version update" 
          git push -f origin master