name: AutoVersion

on:
  schedule:
  - cron: '33 3 * * *'
  push:
    branches: [master]

env:
  AssemblyInfo: ./src/Properties/AssemblyInfo.cs

jobs:
  autoversion:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - id: date
        run: |
          echo "{Month}={date +'%m'}" >> $GITHUB_OUTPUT
          echo "{Year}={date +'%y'}" >> $GITHUB_OUTPUT
          echo "{MonthName}={date +'%B'}" >> $GITHUB_OUTPUT
      - name: Change version
        run: >
          (Get-Content ${{env.AssemblyInfo}}) -replace
          '(?<start>(AssemblyVersion|AssemblyFileVersion)\(\"\d{4}\.)\d{2}(?<end>(\.\*|\.0\.0)"\))',
          "`${start}${{ steps.date.outputs.Month }}`${end}" 
          | Set-Content ${{ env.AssemblyInfo }}
      - name: Commit changes
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git fetch
          git add ${{ env.AssemblyInfo }}
          git commit -m "Auto update version to ${{ steps.date.outputs.MonthName }} ${{ steps.date.outputs.Year }}" 
          git push -f origin master