name: Auto-update version

concurrency:
  group: ${{ github.event_name }}
  cancel-in-progress: true

on:
  schedule:
  - cron: '33 3 * * *'
  workflow_dispatch:

env:
  AssemblyInfo: ./src/Properties/AssemblyInfo.cs

jobs:
  autoversion:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - id: date
        run: |
          echo "Month=$(date +'%m')" >> $env:GITHUB_OUTPUT
          echo "Year=$(date +'%Y')" >> $env:GITHUB_OUTPUT
          echo "MonthName=$(date +'%B')" >> $env:GITHUB_OUTPUT
      - name: Change version
        run: >
          (Get-Content ${{ env.AssemblyInfo }}) 
          -replace '(?<start>(AssemblyVersion|AssemblyFileVersion)\(\")\d{4}\.\d{2}',
          "`${start}${{ steps.date.outputs.Year }}.${{ steps.date.outputs.Month }}" 
          -replace '(?<start>Copyright ©  2012 - )\d{4}',
          "`${start}${{ steps.date.outputs.Year }}" 
          | Set-Content ${{ env.AssemblyInfo }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Auto-update version
          body:
          labels: invalid
          commit-message: Auto-update version to ${{ steps.date.outputs.MonthName }} ${{ steps.date.outputs.Year }}
          branch: autoupdate-version
          delete-branch: true
          reviewers: KirillGutyrchik