name: Test-workflow

# test changes

concurrency:
  group: "${{ github.event_name }} : ${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
    branches: [ master ]
    types: 
    - opened
    - labeled
  workflow_dispatch:

jobs:
  testworkflow:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: Echo
        run: echo "::debug::${{ github.event_name }}"